title: xiling-theme

author: 曦月
avatar: /img/avatar.png  #头像路径
introduction: 欢迎啦~  #欢迎词

menu:
  - home #首页
  - archives #归档
  #- categories #分类
  #- tags #标签
  - about #关于

fixelMenu: false

page:
  maxShowPage: 5

# 默认背景图
backgroundImage: /img/bg.jpg